### PR TITLE
Support configuring RESTAPI to GRPC via HTTPFilterPolicy

### LINKED ISSUE #605: Support configuring RESTAPI to GRPC via HTTPFilterPolicy
### Description

_No response_

### Use Scenes

We can leverage the https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_json_transcoder_filter#config-http-filters-grpc-json-transcoder filter to do it.

Let's add it as a plugin under https://github.com/mosn/htnn/tree/main/controller/plugins.
The test needs to be added under https://github.com/mosn/htnn/tree/main/controller/internal/translation/testdata/plugins. (Maybe we can move the tests to https://github.com/mosn/htnn/tree/main/controller/plugins in a new PR?)

Don't forget to add e2e test under https://github.com/mosn/htnn/tree/main/e2e/tests.
We can setup a GPRC backend using [the image](https://github.com/kubernetes-sigs/gateway-api/blob/836ab809e19010b9d4fca5c7243bb736f4d9aa04/conformance/base/manifests.yaml#L557) from gateway-api repo.

Feel free to submit the doc in a separate PR if this PR is too big.

### Advice

_No response_

### PR DESCRIPTION
**Pull request by hanxiantao**
add grpcJsonTranscoder plugin
fix #605

### CODE REVIEW

**Comment by hanxiantao** [comment]
i will add e2e test later

**Comment by hanxiantao** [comment]
@spacewander After using the grpc_json_transcoder, it appears to load by default
htnn/gateway:e2e error info:
```
2024-06-30T00:30:00.840780Z warning envoy config external/envoy/source/extensions/config_subscription/grpc/grpc_subscription_impl.cc:138 gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_10000: Proto constraint validation failed (field: "descriptor_set", reason: is required):
thread=18
2024-06-30T00:30:01.899953Z warn Envoy proxy is NOT ready: config received from XDS server, but was rejected: cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 1 rejected
2024-06-30T00:30:02.898713Z warn Envoy proxy is NOT ready: config received from XDS server, but was rejected: cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 1 rejected
2024-06-30T00:30:03.899237Z warn Envoy proxy is NOT ready: config received from XDS server, but was rejected: cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 1 rejected
```
istiod error info:
```
2024-06-30T00:32:44.401660Z info ads ADS: "10.244.0.15:48202" default-istio-7b5bfb6c49-d6nn8.e2e-another-35 terminated
2024-06-30T00:33:48.712678Z info delta ADS: "10.244.0.8:51874" istio-ingressgateway-56d5bdc4f5-5kjqx.istio-system-1 terminated
2024-06-30T00:33:49.104493Z info delta ADS: new delta connection for node:istio-ingressgateway-56d5bdc4f5-5kjqx.istio-system-36
2024-06-30T00:33:49.107514Z info delta CDS: PUSH request for node:istio-ingressgateway-56d5bdc4f5-5kjqx.istio-system resources:21 removed:0 size:21.7kB cached:0/20 filtered:0
2024-06-30T00:33:49.110402Z info delta EDS: PUSH request for node:istio-ingressgateway-56d5bdc4f5-5kjqx.istio-system resources:20 removed:0 size:3.2kB empty:4 cached:0/20 filtered:0
2024-06-30T00:33:49.110919Z info delta LDS: PUSH request for node:istio-ingressgateway-56d5bdc4f5-5kjqx.istio-system resources:1 removed:0 size:5.0kB
2024-06-30T00:33:49.165421Z warn delta ADS:LDS: ACK ERROR istio-ingressgateway-56d5bdc4f5-5kjqx.istio-system-36 Internal:Error adding/updating listener(s) 0.0.0.0_18000: Proto constraint validation failed (field: "descriptor_set", reason: is required):
```

**Comment by spacewander** [comment]
> @spacewander After using the grpc_json_transcoder, it appears to load by default htnn/gateway:e2e error info:
> 
> ```
> 2024-06-30T00:30:00.840780Z warning envoy config external/envoy/source/extensions/config_subscription/grpc/grpc_subscription_impl.cc:138 gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_10000: Proto constraint validation failed (field: "descriptor_set", reason: is required):
> thread=18
> 2024-06-30T00:30:01.899953Z warn Envoy proxy is NOT ready: config received from XDS server, but was rejected: cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 1 rejected
> 2024-06-30T00:30:02.898713Z warn Envoy proxy is NOT ready: config received from XDS server, but was rejected: cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 1 rejected
> 2024-06-30T00:30:03.899237Z warn Envoy proxy is NOT ready: config received from XDS server, but was rejected: cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 1 rejected
> ```
> 
> istiod error info:
> 
> ```
> 2024-06-30T00:32:44.401660Z info ads ADS: "10.244.0.15:48202" default-istio-7b5bfb6c49-d6nn8.e2e-another-35 terminated
> 2024-06-30T00:33:48.712678Z info delta ADS: "10.244.0.8:51874" istio-ingressgateway-56d5bdc4f5-5kjqx.istio-system-1 terminated
> 2024-06-30T00:33:49.104493Z info delta ADS: new delta connection for node:istio-ingressgateway-56d5bdc4f5-5kjqx.istio-system-36
> 2024-06-30T00:33:49.107514Z info delta CDS: PUSH request for node:istio-ingressgateway-56d5bdc4f5-5kjqx.istio-system resources:21 removed:0 size:21.7kB cached:0/20 filtered:0
> 2024-06-30T00:33:49.110402Z info delta EDS: PUSH request for node:istio-ingressgateway-56d5bdc4f5-5kjqx.istio-system resources:20 removed:0 size:3.2kB empty:4 cached:0/20 filtered:0
> 2024-06-30T00:33:49.110919Z info delta LDS: PUSH request for node:istio-ingressgateway-56d5bdc4f5-5kjqx.istio-system resources:1 removed:0 size:5.0kB
> 2024-06-30T00:33:49.165421Z warn delta ADS:LDS: ACK ERROR istio-ingressgateway-56d5bdc4f5-5kjqx.istio-system-36 Internal:Error adding/updating listener(s) 0.0.0.0_18000: Proto constraint validation failed (field: "descriptor_set", reason: is required):
> ```

We need to provide a placeholder config for http filter in HTTPFilterConfigPlaceholder. The placeholder config will be validated but won't be used.

I am not sure how deep Envoy will validate the config in https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/grpc_json_transcoder/v3/transcoder.proto#extensions-filters-http-grpc-json-transcoder-v3-grpcjsontranscoder, maybe we can pass a fake pb filename if it doesn't validate the content.

**Comment by hanxiantao** [comment]
> HTTPFilterConfigPlaceholder

Thank you for your help. I've seen similar examples in other code sections, and I will give it a try following your suggestions.

**Comment by hanxiantao** [comment]
> > @spacewander使用grpc_json_transcoder后，似乎默认加载htnn/gateway:e2e错误信息：
> > ```
> > 2024-06-30T00:30:00.840780Z warning envoy config external/envoy/source/extensions/config_subscription/grpc/grpc_subscription_impl.cc:138 gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_10000: Proto constraint validation failed (field: "descriptor_set", reason: is required):
> > thread=18
> > 2024-06-30T00:30:01.899953Z warn Envoy proxy is NOT ready: config received from XDS server, but was rejected: cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 1 rejected
> > 2024-06-30T00:30:02.898713Z warn Envoy proxy is NOT ready: config received from XDS server, but was rejected: cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 1 rejected
> > 2024-06-30T00:30:03.899237Z warn Envoy proxy is NOT ready: config received from XDS server, but was rejected: cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 1 rejected
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > istiod 错误信息：
> > ```
> > 2024-06-30T00:32:44.401660Z info ads ADS: "10.244.0.15:48202" default-istio-7b5bfb6c49-d6nn8.e2e-another-35 terminated
> > 2024-06-30T00:33:48.712678Z info delta ADS: "10.244.0.8:51874" istio-ingressgateway-56d5bdc4f5-5kjqx.istio-system-1 terminated
> > 2024-06-30T00:33:49.104493Z info delta ADS: new delta connection for node:istio-ingressgateway-56d5bdc4f5-5kjqx.istio-system-36
> > 2024-06-30T00:33:49.107514Z info delta CDS: PUSH request for node:istio-ingressgateway-56d5bdc4f5-5kjqx.istio-system resources:21 removed:0 size:21.7kB cached:0/20 filtered:0
> > 2024-06-30T00:33:49.110402Z info delta EDS: PUSH request for node:istio-ingressgateway-56d5bdc4f5-5kjqx.istio-system resources:20 removed:0 size:3.2kB empty:4 cached:0/20 filtered:0
> > 2024-06-30T00:33:49.110919Z info delta LDS: PUSH request for node:istio-ingressgateway-56d5bdc4f5-5kjqx.istio-system resources:1 removed:0 size:5.0kB
> > 2024-06-30T00:33:49.165421Z warn delta ADS:LDS: ACK ERROR istio-ingressgateway-56d5bdc4f5-5kjqx.istio-system-36 Internal:Error adding/updating listener(s) 0.0.0.0_18000: Proto constraint validation failed (field: "descriptor_set", reason: is required):
> > ```
> 
> 我们需要在 HTTPFilterConfigPlaceholder 中为 http 过滤器提供占位符配置。该占位符配置将被验证但不会被使用。
> 
> 我不确定 Envoy 将如何深入验证https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/grpc_json_transcoder/v3/transcoder.proto#extensions-filters-http-grpc-json-transcoder-v3-grpcjsontranscoder中的配置，如果它不验证内容，也许我们可以传递一个假的 pb 文件名。

Thank you for your help. I've seen similar examples in other code sections, and I will give it a try following your suggestions.

**Pull request closed without merging**
