### PR TITLE
feat(makefile, workflows): add YAML linter to workflow and Makefile

### LINKED ISSUE #128: Add yaml linter to lint yaml configuration

### PR DESCRIPTION
**Pull request by am6737**
- Add `lint-yaml` target in Makefile to lint YAML files, ignoring Helm template YAML files
- Update GitHub Actions workflow to include YAML lint step

We don’t use `if ! command -v yamllint` because some environments might have a pre-installed Python version. Checking the specific path ensures we're using the Node.js version to avoid conflicts.

Close #128

### CODE REVIEW

**Comment by am6737** [comment]
Hey @spacewander 

Could you take a look at my PR when you have a chance? Thanks!

**Review by spacewander — APPROVED** [review]

**Comment by spacewander** [comment]
> We don’t use `if ! command -v yamllint` because some environments might have a pre-installed Python version. Checking the specific path ensures we're using the Node.js version to avoid conflicts.

Could you add this reason as a comment in the Makefile?

**Comment by am6737** [comment]
> > We don’t use `if ! command -v yamllint` because some environments might have a pre-installed Python version. Checking the specific path ensures we're using the Node.js version to avoid conflicts.
> 
> Could you add this reason as a comment in the Makefile?

Sure! I’ll add that comment in the Makefile. Thank you for the suggestion!

**Comment by spacewander** [comment]
@am6737 
Merged. Thanks!

**Comment by am6737** [comment]
Hey @spacewander

This PR is marked as "Repository Not Participating" in Hacktoberfest. According to the [Hacktoberfest rules](https://hacktoberfest.com/participation/#pr-mr-details), the repository needs the "hacktoberfest" topic or the PR should be labeled "hacktoberfest-accepted."

If possible, could you please add the "hacktoberfest-accepted" label to this PR?

Thanks a lot!

**Comment by am6737** [comment]
> @am6737 Sorry for forgetting the operation. Label added.

Thank you for your help, everything looks great now!

**Pull request merged**
